// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package http represents the imported interface "foo:bar/http".
package http

import (
	httptypes "github.com/rajatjindal/wasm-tools-gen-issue/internal/foo/bar/http-types"
	"github.com/ydnar/wasm-tools-go/cm"
)

// SendRequest represents the imported function "send-request".
//
//	send-request: func(req: request) -> result<response, http-error>
//
//go:nosplit
func SendRequest(req httptypes.Request) (result cm.OKResult[httptypes.Response, httptypes.HTTPError]) {
	req0, req1, req2, req3, req4, req5, req6, req7, req8, req9 := lower_Request(req)
	wasmimport_SendRequest((uint32)(req0), (*uint8)(req1), (uint32)(req2), (*[2]string)(req3), (uint32)(req4), (*[2]string)(req5), (uint32)(req6), (uint32)(req7), (*uint8)(req8), (uint32)(req9), &result)
	return
}

//go:wasmimport foo:bar/http send-request
//go:noescape
func wasmimport_SendRequest(req0 uint32, req1 *uint8, req2 uint32, req3 *[2]string, req4 uint32, req5 *[2]string, req6 uint32, req7 uint32, req8 *uint8, req9 uint32, result *cm.OKResult[httptypes.Response, httptypes.HTTPError])
